#!/bin/bash
set -e

# Directory this script is in
ROOTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." >/dev/null 2>&1 && pwd)"
SOURCE=$ROOTDIR/src
RUNTIME=$ROOTDIR/runtime

echo '[install] Activating Virtualenv...'
source $RUNTIME/bin/activate

echo "[install] Activated. Running <pip install ${@:2}>..."

pip install ${@:1}
pip freeze > $SOURCE/requirements.txt

echo "[cmd] Install Succeeded. Deactivating Virtualenv"
deactivate

exit $?
